version: 2
jobs:
  build:
    docker:
      - image: docker:stable-git
    steps:
      - checkout
      - run: sudo apt-get update && sudo apt-get make
      - setup_remote_docker:
          version: 18.05.0-ce
      - run: cd docker && make build
      - run: docker login -u $DOCKER_HUB_USER_ID -p $DOCKER_HUB_PWD
      - run: docker-compose push