version: 2
jobs:
  build:
    docker:
      - image: ubuntu:18.04
    steps:
      - checkout
      - run: apt-get update && apt-get install make
      - setup_remote_docker:
          version: 18.05.0-ce
      - run: cd docker && make build
      - run: docker login -u $DOCKER_HUB_USER_ID -p $DOCKER_HUB_PWD
      - run: docker-compose push